-- DDL
CREATE TABLE `TAB_USERS` (
	USERNAME varchar(20) NOT NULL PRIMARY KEY,
	PASSWORD varchar(20) NOT NULL
);

CREATE TABLE `TAB_ROLES` (
	ROLENAME varchar(20) NOT NULL PRIMARY KEY
);

CREATE TABLE `TAB_USERS_ROLES` (
	USERNAME varchar(20) NOT NULL,
	ROLENAME varchar(20) NOT NULL,
	PRIMARY KEY (USERNAME, ROLENAME),
	CONSTRAINT TAB_USERS_ROLES_fk1 FOREIGN KEY (USERNAME) REFERENCES TAB_USERS (USERNAME),
	CONSTRAINT TAB_USERS_ROLES_fk2 FOREIGN KEY (ROLENAME) REFERENCES TAB_ROLES (ROLENAME)
);
-- Data
INSERT INTO `TAB_USERS` (`USERNAME`, `PASSWORD`) VALUES ('admin', 'admin');
INSERT INTO `TAB_USERS` (`USERNAME`, `PASSWORD`) VALUES ('op', 'op');
INSERT INTO `TAB_ROLES` (`ROLENAME`) VALUES ('administrator');
INSERT INTO `TAB_ROLES` (`ROLENAME`) VALUES ('operator');
INSERT INTO `TAB_USERS_ROLES` (`USERNAME`, `ROLENAME`) VALUES ('admin', 'administrator');
INSERT INTO `TAB_USERS_ROLES` (`USERNAME`, `ROLENAME`) VALUES ('admin', 'operator');
INSERT INTO `TAB_USERS_ROLES` (`USERNAME`, `ROLENAME`) VALUES ('op', 'operator');